# Generated by Django 5.2 on 2025-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagerecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('event', models.TextField()),
                ('people', models.JSONField()),
            ],
            options={
                'db_table': 'imagerecord',
                'managed': False,
            },
        ),
    ]
