name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # run on both Linux and Windows so you match your local Win32 env
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # if you have a requirements.txt at repo root:
          pip install -r requirements.txt
          # otherwise, list them directly:
          # pip install opencv-python-headless pytest mtcnn deepface

      - name: Run face-track tests
        run: python -m pytest facetrack/facetrack_tests.py